context.modules = [
    {   name = libpipewire-module-spdif-encode
        args = {
            # codec = ac3          # ac3 or dts (default: ac3)
            # bitrate = 448000     # encoder bitrate in bps
            # target.object = ""   # target S/PDIF device name
        }
    }
]
