context.modules = [
    {   name = libpipewire-module-spdif-encode
        args = {
            # target.object = ""   # target S/PDIF/HDMI device name (e.g. "alsa_output.pci-0000_01_00.1.hdmi-stereo")
        }
    }
]
